# permissions for end users to edit netplanconfigs.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: netplan-operator
    app.kubernetes.io/managed-by: kustomize
  name: netplanconfig-editor-role
rules:
- apiGroups:
  - network.netplan.io
  resources:
  - netplanconfigs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - network.netplan.io
  resources:
  - netplanconfigs/status
  verbs:
  - get
